---
language: python
python: 2.7

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install ansible
- echo localhost > hosts
- echo -e "[defaults]\nroles_path = ../" > ansible.cfg

script:
- ansible-playbook -i hosts tests/test.yml --syntax-check
- ansible-playbook -i hosts tests/test.yml --connection=local -s | grep -q "ok=2  *changed=2"
- ansible-playbook -i hosts tests/test.yml --connection=local -s | grep -q "ok=1  *changed=0"
- sudo apt-get -qq remove puppetlabs-release
- ansible-playbook -i hosts tests/test.yml --connection=local -s | grep -q "ok=2  *changed=2"
