---
- name: Detect Puppetlabs release package
  command: dpkg-query -f '${Package} ${Status}' -W puppetlabs-release
  register: release_package
  changed_when: not release_package.stdout.startswith("puppetlabs-release install ")

- name: Download Puppetlabs release package
  shell: "wget http://apt.puppetlabs.com/{{ release_pkg }} -O {{ release_file }} && dpkg -i {{ release_file }} && rm -f {{ release_file }}"
  when: release_package.changed
