---
- name: Detect Puppetlabs release package
  command: dpkg-query -f '${Package} ${Status}' -W puppetlabs-release
  register: release_package
  failed_when: release_package.rc > 1
  changed_when: not release_package.stdout.startswith("puppetlabs-release install ")
  notify: Install package
